#ifndef ERROR_CODE_H
#define ERROR_CODE_H

enum retcode_t{
    ERROR_OK = 0,
    ERROR_UNKNOWN = 1,

    ERROR_PACK_SEND_HEADER_LENGTH = 10000,
    ERROR_PACK_PROTO_SERIALIZE = 10001,
    ERROR_PACK_SEND_PAYLOAD = 10002,
    ERROR_PACK_RECV_HEADER_LENGTH = 10010,
    ERROR_PACK_PROTO_PARSE = 10011,
    ERROR_PACK_RECV_PAYLOAD = 10012,

    ERROR_DB_INIT_ERROR = 20000,
    ERROR_DB_SELECT_ERROR = 20001,
    ERROR_DB_INSERT_ERROR = 20002,
    ERROR_DB_UPDATE_ERROR = 20003,
};

const char* errmsg(retcode_t ret);

#endif
